### ISSUE TITLE
Ability to play avi\mkv videos

### ISSUE THREAD

**Issue by shizzgar** [RblSb/SyncTube#39]
Hi, @RblSb!
First of all, thank you for your job!
It works like a charm with ifames and mp4 videos. 
Now i have no problem to sync video with my girlfriend!)
Keep same way :)

But a like to download some videos from different sources, 
And some times it's only mkv\avi is available. Is it possible 
to add mkv\avi support for your [SyncTube](https://github.com/RblSb/SyncTube) ?)

Thank you in advance!

**Comment by RblSb** [comment]
Sadly there is no browser support for these containers, so you need to convert them with ffmpeg or similar tool for yourself first.
If video has [supported in web codecs](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#common_codecs), you can recreate `mkv/avi` containers to `mp4` with tools like Mkvtoolnix, instead of re-rendering video.
